name: SmallRnaPipe
channels :
	- conda-forge
	- bionconda
dependencies:
	- bwa=0.7.17
	- cutadapt=3.4
	- fastqc=0.11.7
	- mmquant=ba73efb
	- multiqc=1.7
	- prinseq-lite=0.20.4
	- samtools=1.9
	- srnaMapper=d64c89d
	- trim-galore=0.6.5
