name: SmallRnaPipe
channels :
  - conda-forge
  - bioconda
dependencies:
  - bwa=0.7.17
  - cutadapt=3.4
  - fastqc=0.11.7
  - multiqc=1.11
  - PRINSEQ=0.20.4
  - samtools=1.9
  - trim-galore=0.6.5
  - perl=5.26.2
  - datamash=1.1.0
  - nextflow=21.04.0
  - srnamapper=1.0.7
  - mmquant=1.0.4
  - mirdeep2=2.0.1.2
